plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.51-beta'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        emperoreye {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
}
