      - name: Make Gradle executable
        run: |
          chmod +x "$PROJECT_DIR/gradlew"

      - name: Fix local dependencies
        run: |
          sed -i "s/implementation fg.deobf(files(/implementation files(/g" "$PROJECT_DIR/build.gradle"

          echo "=== Dépendances corrigées ==="
          grep -n "implementation files" "$PROJECT_DIR/build.gradle"

      - name: Build JAR
        run: |
          cd "$PROJECT_DIR"
          ./gradlew build --no-daemon --stacktrace

      - name: Show build outputs
        if: always()
        run: |
          echo "=== PROJECT_DIR ==="
          echo "$PROJECT_DIR"

          echo "=== BUILD/LIBS ==="
          if [ -d "$PROJECT_DIR/build/libs" ]; then
            ls -lah "$PROJECT_DIR/build/libs"
          else
            echo "build/libs n'existe pas."
          fi

          echo "=== TOUS LES JAR ==="
          find "$PROJECT_DIR" -type f -name "*.jar" -print || true

      - name: Upload JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: EmperorEyeRevemp-JAR
          path: "${{ env.PROJECT_DIR }}/build/libs/*.jar"
          if-no-files-found: error
